### ISSUE TITLE
Screenshot is gone

### ISSUE THREAD

**Issue by remram44** [guyzmo/FFTabsOutliner#3]
The screenshot link in the README is 404.

**Comment by ShervinM** [comment]
The whole project is a 404, no work since 2013

**Comment by guyzmo** [comment]
well, technically it's not exactly 404, it's just taking dust 😄 

basically, that was just an experiment at doing the thing, but that has been made complicated because of firefox multiple changes in API. I think that project predate the full WebExtension switch, and is using the jetpack API that has since been replaced. If anybody is willing to recreate something similar but for latest API, or scavenge this code into something new but FLOSS, I'll be happy to give him the domain!

I'll have a look and put back the screenshot in place anyway. I guess there's still stuff to be saved to bring back to life the project.

**Comment by guyzmo** [comment]
fixed, ♥

**Comment by devinrhode2** [comment]
Just looked at the code tab and noticed most changes say "6 years ago"
My question is - @guyzmo - how much code do you think could be used from tabs outliner without the author having an issue with it? I want to just port tabs outliner but sharing the ported extension might not be something the author would want

I looked through incompatibilities and searched the code for those apis, here are some notes for things not supported in FF that are used in tabs outliner source code:
manifest.json options_page
tabs.getAllInWindow
tabs.onReplaced
tabs.onSelectionChanged

downloads: FilenameConflictAction.prompt, drag
events
notifications.update?
permissions.onRemoved?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by tg-x** [comment]
If you mean code reuse from TabOutliner for Chrome,
it does not have an open source license last I checked thus can't use code from there.

However, there's the [TabFern](https://github.com/cxw42/TabFern) extension which is open source,
but it does not yet work with Firefox, it's still [work in progress](https://github.com/cxw42/TabFern/issues/100)

**Comment by cxw42** [comment]
@tg-x Thanks for spreading the word about TabFern!  @devinrhode2 I agree with @tg-x --- please don't use any code from Tabs Outliner.

@guyzmo TF indeed uses the latest API and I welcome any contributions :D .

**Comment by guyzmo** [comment]
Hi! At the time I wrote this extension, the webextension API was very early stage, and most of the needed API wasn't exposed, and some of it was going to be deprecated. Now many things have changed.

@tg-x  About TO for chrome, the author is pretty clear that he does not want to share anything, and when I reused some of his icons assets, he told me to not use anything from him. So I did change the assets accordingly.

@cxw42 thank you for 'forking' the idea in a FLOSS way, and of course, all the work here, for what it's worth, is there to be improved upon, reused, forked, changed… Be my guest!

 Since 2013, I've been busy on so many projects, that I don't have time to give to this project anymore ☹
